spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /demo/api/v1